# Generated by Django 4.1.4 on 2022-12-31 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='featured_product_id',
        ),
        migrations.AddField(
            model_name='collection',
            name='featured_product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.product'),
        ),
    ]
